INSERT IGNORE INTO armor_category (id, name) VALUES (1, 'SOFT_LEATHER');
INSERT IGNORE INTO armor_category (id, name) VALUES (2, 'BOILED_LEATHER');
INSERT IGNORE INTO armor_category (id, name) VALUES (3, 'MAIL');
INSERT IGNORE INTO armor_category (id, name) VALUES (4, 'PLATE');

INSERT IGNORE INTO armor_penalty(id, name) VALUES (1, 'MINUS_TEN_PERCEPTION');
INSERT IGNORE INTO armor_penalty(id, name) VALUES (2, 'MINUS_TEN_STEALTH');
INSERT IGNORE INTO armor_penalty(id, name) VALUES (3, 'MINUS_TWENTY_PERCEPTION');

INSERT IGNORE INTO armor_quality (id, name) VALUES (1, 'FLEXIBLE');
INSERT IGNORE INTO armor_quality (id, name) VALUES (2, 'IMPENETRABLE');
INSERT IGNORE INTO armor_quality (id, name) VALUES (3, 'PARTIAL');
INSERT IGNORE INTO armor_quality (id, name) VALUES (4, 'WEAKPOINTS');
INSERT IGNORE INTO armor_quality (id, name) VALUES (5, 'DURABLE');
INSERT IGNORE INTO armor_quality (id, name) VALUES (6, 'FINE');
INSERT IGNORE INTO armor_quality (id, name) VALUES (7, 'LIGHTWEIGHT');
INSERT IGNORE INTO armor_quality (id, name) VALUES (8, 'PRACTICAL');
INSERT IGNORE INTO armor_quality (id, name) VALUES (9, 'UGLY');
INSERT IGNORE INTO armor_quality (id, name) VALUES (10, 'SHODDY');
INSERT IGNORE INTO armor_quality (id, name) VALUES (11, 'UNRELIABLE');

INSERT IGNORE INTO body_localization(id, name) VALUES (1, 'HEAD');
INSERT IGNORE INTO body_localization(id, name) VALUES (2, 'RIGHT_ARM');
INSERT IGNORE INTO body_localization(id, name) VALUES (3, 'LEFT_ARM');
INSERT IGNORE INTO body_localization(id, name) VALUES (4, 'BODY');
INSERT IGNORE INTO body_localization(id, name) VALUES (5, 'RIGHT_LEG');
INSERT IGNORE INTO body_localization(id, name) VALUES (6, 'LEFT_LEG');

INSERT IGNORE INTO weapon_group(id, name) VALUES (1, 'BASIC');
INSERT IGNORE INTO weapon_group(id, name) VALUES (2, 'CAVALRY');
INSERT IGNORE INTO weapon_group(id, name) VALUES (3, 'FENCING');
INSERT IGNORE INTO weapon_group(id, name) VALUES (4, 'BRAWLING');
INSERT IGNORE INTO weapon_group(id, name) VALUES (5, 'FLAIL');
INSERT IGNORE INTO weapon_group(id, name) VALUES (6, 'PARRY');
INSERT IGNORE INTO weapon_group(id, name) VALUES (7, 'POLEARM');
INSERT IGNORE INTO weapon_group(id, name) VALUES (8, 'TWO_HANDED');
INSERT IGNORE INTO weapon_group(id, name) VALUES (9, 'BLACKPOWDER');
INSERT IGNORE INTO weapon_group(id, name) VALUES (10, 'BOW');
INSERT IGNORE INTO weapon_group(id, name) VALUES (11, 'CROSSBOW');
INSERT IGNORE INTO weapon_group(id, name) VALUES (12, 'ENGINEERING');
INSERT IGNORE INTO weapon_group(id, name) VALUES (13, 'ENTANGLING');
INSERT IGNORE INTO weapon_group(id, name) VALUES (14, 'EXPLOSIVES');
INSERT IGNORE INTO weapon_group(id, name) VALUES (15, 'SLING');
INSERT IGNORE INTO weapon_group(id, name) VALUES (16, 'THROWING');

INSERT IGNORE INTO weapon_quality(id, name) VALUES (1, 'ACCURATE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (2, 'BLACKPOWDER');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (3, 'BLAST');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (4, 'DAMAGING');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (5, 'DEFENSIVE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (6, 'DISTRACT');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (7, 'ENTANGLE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (8, 'FAST');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (9, 'HACK');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (10, 'IMPACT');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (11, 'IMPALE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (12, 'PENETRATING');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (13, 'PISTOL');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (14, 'PRECISE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (15, 'PUMMEL');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (16, 'REPEATER');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (17, 'SHIELD');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (18, 'TRAP_BLADE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (19, 'TWO_HANDED');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (20, 'UNBREAKABLE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (21, 'WRAP');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (22, 'DANGEROUS');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (23, 'IMPRECISE');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (24, 'RELOAD');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (25, 'SLOW');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (26, 'TIRING');
INSERT IGNORE INTO weapon_quality(id, name) VALUES (27, 'UNDAMAGING');

INSERT IGNORE INTO weapon_reach(id, name) VALUES (1, 'AVERAGE');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (2, 'LONG');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (3, 'MASSIVE');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (4, 'PERSONAL');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (5, 'RANGED');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (6, 'SHORT');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (7, 'VARIES');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (8, 'VERY_LONG');
INSERT IGNORE INTO weapon_reach(id, name) VALUES (9, 'VERY_SHORT');

INSERT IGNORE INTO weapon_type(id, name) VALUES (1, 'MELEE');
INSERT IGNORE INTO weapon_type(id, name) VALUES (2, 'RANGED');

INSERT IGNORE INTO skill(id, name) VALUE (1, 'ART_CARTOGRAPHY');
INSERT IGNORE INTO skill(id, name) VALUE (2, 'ART_ENGRAVING');
INSERT IGNORE INTO skill(id, name) VALUE (3, 'ART_MOSAICS');
INSERT IGNORE INTO skill(id, name) VALUE (4, 'ART_PAINTING');
INSERT IGNORE INTO skill(id, name) VALUE (5, 'ART_SCULPTURE');
INSERT IGNORE INTO skill(id, name) VALUE (6, 'ART_TATTOO');
INSERT IGNORE INTO skill(id, name) VALUE (7, 'ART_WEAVING');
INSERT IGNORE INTO skill(id, name) VALUE (8, 'ATHLETICS');
INSERT IGNORE INTO skill(id, name) VALUE (9, 'BRIBERY');
INSERT IGNORE INTO skill(id, name) VALUE (10, 'CHARM');
INSERT IGNORE INTO skill(id, name) VALUE (11, 'CHARM_ANIMAL');
INSERT IGNORE INTO skill(id, name) VALUE (12, 'CLIMB');
INSERT IGNORE INTO skill(id, name) VALUE (13, 'COOL');
INSERT IGNORE INTO skill(id, name) VALUE (14, 'CONSUME_ALCOHOL');
INSERT IGNORE INTO skill(id, name) VALUE (15, 'DODGE');
INSERT IGNORE INTO skill(id, name) VALUE (16, 'DRIVE');
INSERT IGNORE INTO skill(id, name) VALUE (17, 'ENDURANCE');
INSERT IGNORE INTO skill(id, name) VALUE (18, 'ENTERTAIN_ACTING');
INSERT IGNORE INTO skill(id, name) VALUE (19, 'ENTERTAIN_COMEDY');
INSERT IGNORE INTO skill(id, name) VALUE (20, 'ENTERTAIN_SINGING');
INSERT IGNORE INTO skill(id, name) VALUE (21, 'ENTERTAIN_STORYTELLING');
INSERT IGNORE INTO skill(id, name) VALUE (22, 'GAMBLE');
INSERT IGNORE INTO skill(id, name) VALUE (23, 'GOSSIP');
INSERT IGNORE INTO skill(id, name) VALUE (24, 'HAGGLE');
INSERT IGNORE INTO skill(id, name) VALUE (25, 'INTIMIDATE');
INSERT IGNORE INTO skill(id, name) VALUE (26, 'INTUITION');
INSERT IGNORE INTO skill(id, name) VALUE (27, 'LEADERSHIP');
INSERT IGNORE INTO skill(id, name) VALUE (28, 'MELEE_BASIC');
INSERT IGNORE INTO skill(id, name) VALUE (29, 'MELEE_BRAWLING');
INSERT IGNORE INTO skill(id, name) VALUE (30, 'MELEE_CAVALRY');
INSERT IGNORE INTO skill(id, name) VALUE (31, 'MELEE_FENCING');
INSERT IGNORE INTO skill(id, name) VALUE (32, 'MELEE_FLAIL');
INSERT IGNORE INTO skill(id, name) VALUE (33, 'MELEE_PARRY');
INSERT IGNORE INTO skill(id, name) VALUE (34, 'MELEE_POLEARM');
INSERT IGNORE INTO skill(id, name) VALUE (35, 'MELEE_TWO_HANDED');
INSERT IGNORE INTO skill(id, name) VALUE (36, 'NAVIGATION');
INSERT IGNORE INTO skill(id, name) VALUE (37, 'OUTDOOR_SURVIVAL');
INSERT IGNORE INTO skill(id, name) VALUE (38, 'PERCEPTION');
INSERT IGNORE INTO skill(id, name) VALUE (39, 'RIDE_DEMIGRYPH');
INSERT IGNORE INTO skill(id, name) VALUE (40, 'RIDE_GREAT_WOLF');
INSERT IGNORE INTO skill(id, name) VALUE (41, 'RIDE_GRIFFON');
INSERT IGNORE INTO skill(id, name) VALUE (42, 'RIDE_HORSE');
INSERT IGNORE INTO skill(id, name) VALUE (43, 'RIDE_PEGASUS');
INSERT IGNORE INTO skill(id, name) VALUE (44, 'ROW');
INSERT IGNORE INTO skill(id, name) VALUE (45, 'STEALTH_RURAL');
INSERT IGNORE INTO skill(id, name) VALUE (46, 'STEALTH_UNDERGROUND');
INSERT IGNORE INTO skill(id, name) VALUE (47, 'STEALTH_URBAN');
INSERT IGNORE INTO skill(id, name) VALUE (48, 'ANIMAL_CARE');
INSERT IGNORE INTO skill(id, name) VALUE (49, 'ANIMAL_TRAINING_DEMIGRYPH');
INSERT IGNORE INTO skill(id, name) VALUE (50, 'ANIMAL_TRAINING_DOG');
INSERT IGNORE INTO skill(id, name) VALUE (51, 'ANIMAL_TRAINING_HORSE');
INSERT IGNORE INTO skill(id, name) VALUE (52, 'ANIMAL_TRAINING_PEGASUS');
INSERT IGNORE INTO skill(id, name) VALUE (53, 'ANIMAL_TRAINING_PIGEON');
INSERT IGNORE INTO skill(id, name) VALUE (54, 'CHANNELLING_AQSHY');
INSERT IGNORE INTO skill(id, name) VALUE (55, 'CHANNELLING_AZYR');
INSERT IGNORE INTO skill(id, name) VALUE (56, 'CHANNELLING_CHAMON');
INSERT IGNORE INTO skill(id, name) VALUE (57, 'CHANNELLING_DHAR');
INSERT IGNORE INTO skill(id, name) VALUE (58, 'CHANNELLING_GHUR');
INSERT IGNORE INTO skill(id, name) VALUE (59, 'CHANNELLING_GHYRAN');
INSERT IGNORE INTO skill(id, name) VALUE (60, 'CHANNELLING_HYSH');
INSERT IGNORE INTO skill(id, name) VALUE (61, 'CHANNELLING_SHYISH');
INSERT IGNORE INTO skill(id, name) VALUE (62, 'CHANNELLING_ULGU');
INSERT IGNORE INTO skill(id, name) VALUE (63, 'EVALUATE');
INSERT IGNORE INTO skill(id, name) VALUE (64, 'HEAL');
INSERT IGNORE INTO skill(id, name) VALUE (65, 'LANGUAGE_BATTLE_TONGUE');
INSERT IGNORE INTO skill(id, name) VALUE (66, 'LANGUAGE_BRETONNIAN');
INSERT IGNORE INTO skill(id, name) VALUE (67, 'LANGUAGE_CLASSICAL');
INSERT IGNORE INTO skill(id, name) VALUE (68, 'LANGUAGE_GUILDER');
INSERT IGNORE INTO skill(id, name) VALUE (69, 'LANGUAGE_KHAZALID');
INSERT IGNORE INTO skill(id, name) VALUE (70, 'LANGUAGE_MAGICK');
INSERT IGNORE INTO skill(id, name) VALUE (71, 'LANGUAGE_THIEF');
INSERT IGNORE INTO skill(id, name) VALUE (72, 'LANGUAGE_TILEAN');
INSERT IGNORE INTO skill(id, name) VALUE (73, 'LORE_ENGINEERING');
INSERT IGNORE INTO skill(id, name) VALUE (74, 'LORE_GEOLOGY');
INSERT IGNORE INTO skill(id, name) VALUE (75, 'LORE_HERALDRY');
INSERT IGNORE INTO skill(id, name) VALUE (76, 'LORE_HISTORY');
INSERT IGNORE INTO skill(id, name) VALUE (77, 'LORE_LAW');
INSERT IGNORE INTO skill(id, name) VALUE (78, 'LORE_MAGICK');
INSERT IGNORE INTO skill(id, name) VALUE (79, 'LORE_METALLURGY');
INSERT IGNORE INTO skill(id, name) VALUE (80, 'LORE_SCIENCE');
INSERT IGNORE INTO skill(id, name) VALUE (81, 'LORE_THEOLOGY');
INSERT IGNORE INTO skill(id, name) VALUE (82, 'PERFORM_ACROBATICS');
INSERT IGNORE INTO skill(id, name) VALUE (83, 'PERFORM_CLOWNING');
INSERT IGNORE INTO skill(id, name) VALUE (84, 'PERFORM_DANCING');
INSERT IGNORE INTO skill(id, name) VALUE (85, 'PERFORM_FIREBREATHING');
INSERT IGNORE INTO skill(id, name) VALUE (86, 'PERFORM_JUGGLING');
INSERT IGNORE INTO skill(id, name) VALUE (87, 'PERFORM_MIMING');
INSERT IGNORE INTO skill(id, name) VALUE (88, 'PERFORM_ROPE_WALKING');
INSERT IGNORE INTO skill(id, name) VALUE (89, 'PICK_LOCK');
INSERT IGNORE INTO skill(id, name) VALUE (90, 'PLAY_BAGPIPE');
INSERT IGNORE INTO skill(id, name) VALUE (91, 'PLAY_LUTE');
INSERT IGNORE INTO skill(id, name) VALUE (92, 'PLAY_HARP');
INSERT IGNORE INTO skill(id, name) VALUE (93, 'PLAY_HORN');
INSERT IGNORE INTO skill(id, name) VALUE (94, 'PLAY_VIOLIN');
INSERT IGNORE INTO skill(id, name) VALUE (95, 'PRAY');
INSERT IGNORE INTO skill(id, name) VALUE (96, 'RANGED_BLACKPOWDER');
INSERT IGNORE INTO skill(id, name) VALUE (97, 'RANGED_BOW');
INSERT IGNORE INTO skill(id, name) VALUE (98, 'RANGED_CROSSBOW');
INSERT IGNORE INTO skill(id, name) VALUE (99, 'RANGED_ENGINEERING');
INSERT IGNORE INTO skill(id, name) VALUE (100, 'RANGED_ENTANGLING');
INSERT IGNORE INTO skill(id, name) VALUE (101, 'RANGED_EXPLOSIVES');
INSERT IGNORE INTO skill(id, name) VALUE (102, 'RANGED_SLING');
INSERT IGNORE INTO skill(id, name) VALUE (103, 'RANGED_THROWING');
INSERT IGNORE INTO skill(id, name) VALUE (104, 'RESEARCH');
INSERT IGNORE INTO skill(id, name) VALUE (105, 'SAIL_BARGE');
INSERT IGNORE INTO skill(id, name) VALUE (106, 'SAIL_CARAVEL');
INSERT IGNORE INTO skill(id, name) VALUE (107, 'SAIL_COG');
INSERT IGNORE INTO skill(id, name) VALUE (108, 'SAIL_FRIGATE');
INSERT IGNORE INTO skill(id, name) VALUE (109, 'SAIL_WOLFSHIP');
INSERT IGNORE INTO skill(id, name) VALUE (110, 'SECRET_SIGNS_GREY_ORDER');
INSERT IGNORE INTO skill(id, name) VALUE (111, 'SECRET_SIGNS_GUILD');
INSERT IGNORE INTO skill(id, name) VALUE (112, 'SECRET_SIGNS_RANGER');
INSERT IGNORE INTO skill(id, name) VALUE (113, 'SECRET_SIGNS_SCOUT');
INSERT IGNORE INTO skill(id, name) VALUE (114, 'SECRET_SIGNS_THIEF');
INSERT IGNORE INTO skill(id, name) VALUE (115, 'SECRET_SIGNS_VAGABOND');
INSERT IGNORE INTO skill(id, name) VALUE (116, 'SET_TRAP');
INSERT IGNORE INTO skill(id, name) VALUE (117, 'SLEIGHT_OF_HAND');
INSERT IGNORE INTO skill(id, name) VALUE (118, 'SWIM');
INSERT IGNORE INTO skill(id, name) VALUE (119, 'TRACK');
INSERT IGNORE INTO skill(id, name) VALUE (120, 'TRADE_APOTHECARY');
INSERT IGNORE INTO skill(id, name) VALUE (121, 'TRADE_CALLIGRAPHER');
INSERT IGNORE INTO skill(id, name) VALUE (122, 'TRADE_CHANDLER');
INSERT IGNORE INTO skill(id, name) VALUE (123, 'TRADE_CARPENTER');
INSERT IGNORE INTO skill(id, name) VALUE (124, 'TRADE_COOK');
INSERT IGNORE INTO skill(id, name) VALUE (125, 'TRADE_EMBALMER');
INSERT IGNORE INTO skill(id, name) VALUE (126, 'TRADE_SMITH');
INSERT IGNORE INTO skill(id, name) VALUE (127, 'TRADE_TANNER');

INSERT IGNORE INTO talent(id, name, max_level) VALUE (1, 'ACCURATE_SHOT', 'BSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (2, 'ACUTE_SENSE_SIGHT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (3, 'ACUTE_SENSE_SMELL', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (4, 'ACUTE_SENSE_HEARING', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (5, 'ACUTE_SENSE_FEEL', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (6, 'ACUTE_SENSE_TASTE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (7, 'AETHYRIC_ATTUNEMENT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (8, 'ALLEY_CAT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (9, 'AMBIDEXTROUS', '2');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (10, 'ANIMAL_AFFINITY', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (11, 'ARCANE_MAGIC_BEASTS', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (12, 'ARCANE_MAGIC_DEATH', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (13, 'ARCANE_MAGIC_FIRE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (14, 'ARCANE_MAGIC_HEAVENS', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (15, 'ARCANE_MAGIC_METAL', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (16, 'ARCANE_MAGIC_SHADOW', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (17, 'ARCANE_MAGIC_LIGHT', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (18, 'ARCANE_MAGIC_LIFE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (19, 'ARCANE_MAGIC_HEDGECRAFT', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (20, 'ARCANE_MAGIC_NECROMANCY', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (21, 'ARGUMENTATIVE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (22, 'ARTISTIC', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (23, 'ATTRACTIVE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (24, 'BATTLE_RAGE', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (25, 'BEAT_BLADE', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (26, 'BENEATH_NOTICE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (27, 'BERSERK_CHARGE', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (28, 'BLATHER', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (29, 'BLESS_MANANN', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (30, 'BLESS_MORR', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (31, 'BLESS_MYRMIDIA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (32, 'BLESS_RANALD', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (33, 'BLESS_RHYA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (34, 'BLESS_SHALLYA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (35, 'BLESS_SIGMAR', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (36, 'BLESS_TAAL', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (37, 'BLESS_ULRIC', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (38, 'BLESS_VERENA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (39, 'BOOKISH', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (40, 'BREAK_AND_ENTER', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (41, 'BRIBER', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (42, 'CARDSHARP', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (43, 'CAREFUL_STRIKE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (44, 'CAROUSER', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (45, 'CATFALL', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (46, 'CAT_TONGUED', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (47, 'CHAOS_MAGIC_NURGLE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (48, 'CHAOS_MAGIC_SLAANESH', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (49, 'CHAOS_MAGIC_TZEENTCH', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (50, 'COMBAT_AWARE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (51, 'COMBAT_MASTER', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (52, 'COMBAT_REFLEXES', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (53, 'COMMANDING_PRESENCE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (54, 'CONCOCT', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (55, 'CONTORTIONIST', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (56, 'COOLHEADED', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (57, 'CRACK_THE_WHIP', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (58, 'CRAFTSMAN', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (59, 'CRIMINAL', 'NONE');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (60, 'DEADEYE_SHOT', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (61, 'DEALMAKER', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (62, 'DETECT_ARTEFACT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (63, 'DICEMAN', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (64, 'DIRTY_FIGHTING', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (65, 'DISARM', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (66, 'DISTRACT', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (67, 'DOOMED', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (68, 'DRILLED', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (69, 'DUAL_WIELDER', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (70, 'EMBEZZLE', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (71, 'ENCLOSED_FIGHTER', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (72, 'ETIQUETTE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (73, 'FAST_HANDS', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (74, 'FAST_SHOT', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (75, 'FEARLESS_BEASTMEN', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (76, 'FEARLESS_GREENSKINS', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (77, 'FEARLESS_OUTLAWS', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (78, 'FEARLESS_VAMPIRES', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (79, 'FEARLESS_WATCHMEN', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (80, 'FEARLESS_WITCHES', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (81, 'FEINT', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (82, 'FIELD_DRESSING', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (83, 'FISHERMAN', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (84, 'FLAGELLANT', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (85, 'FLEE', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (86, 'FLEET_FOOTED', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (87, 'FRENZY', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (88, 'FRIGHTENING', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (89, 'FURIOUS_ASSAULT', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (90, 'GREGARIOUS', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (91, 'GUNNER', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (92, 'HARDY', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (93, 'HATRED_BEASTMEN', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (94, 'HATRED_GRENSKINS', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (95, 'HATRED_MONSTERS', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (96, 'HATRED_OUTLAWS', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (97, 'HATRED_SIGMARITES', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (98, 'HATRED_UNDEAD', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (99, 'HATRED_WITCHES', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (100, 'HOLY_HATRED', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (101, 'HOLY_VISIONS', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (102, 'HUNTERS_EYE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (103, 'IMPASSIONED_ZEAL', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (104, 'IMPLACABLE', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (105, 'IN_FIGHTER', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (106, 'INSPIRING', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (107, 'INSTINCTIVE_DICTION', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (108, 'INVOKE_MANANN', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (109, 'INVOKE_MORR', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (110, 'INVOKE_MYRMIDIA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (111, 'INVOKE_RANALD', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (112, 'INVOKE_RHYA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (113, 'INVOKE_SHALLYA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (114, 'INVOKE_SIGMAR', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (115, 'INVOKE_TAAL', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (116, 'INVOKE_ULRIC', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (117, 'INVOKE_VERENA', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (118, 'IRON_JAW', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (119, 'IRON_WILL', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (120, 'JUMP_UP', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (121, 'KINGPIN', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (122, 'LIGHTNING_REFLEXES', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (123, 'LINGUISTICS', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (124, 'LIP_READING', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (125, 'LUCK', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (126, 'MAGICAL_SENSE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (127, 'MAGIC_RESISTANCE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (128, 'MAGNUM_OPUS', 'NONE');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (129, 'MARKSMAN', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (130, 'MASTER_OF_DISGUISE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (131, 'MASTER_ORATOR', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (132, 'MASTER_TRADESMAN', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (133, 'MENACING', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (134, 'MIMIC', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (135, 'NIGHT_VISION', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (136, 'NIMBLE_FINGERED', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (137, 'NOBLE_BLOOD', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (138, 'NOSE_FOR_TROUBLE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (139, 'NUMISMATICS', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (140, 'OLD_SALT', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (141, 'ORIENTATION', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (142, 'PANHANDLE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (143, 'PERFECT_PITCH', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (144, 'PETTY_MAGIC', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (145, 'PHARMACIST', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (146, 'PILOT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (147, 'PUBLIC_SPEAKER', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (148, 'PURE_SOUL', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (149, 'RAPID_RELOAD', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (150, 'REACTION_STRIKE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (151, 'READ_WRITE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (152, 'RELENTLESS', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (153, 'RESISTANCE', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (154, 'RESOLUTE', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (155, 'REVERSAL', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (156, 'RIPOSTE', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (157, 'RIVER_GUIDE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (158, 'ROBUST', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (159, 'ROUGHRIDER', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (160, 'ROVER', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (161, 'SAVANT', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (162, 'SAVVY', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (163, 'SCALE_SHEER_SURFACE', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (164, 'SCHEMER', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (165, 'SEA_LEGS', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (166, 'SEASONED_TRAVELLER', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (167, 'SECOND_SIGHT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (168, 'SECRET_IDENTITY', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (169, 'SHADOW', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (170, 'SHARP', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (171, 'SHARPSHOOTER', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (172, 'SHIELDSMAN', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (173, 'SIXTH_SENSE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (174, 'SLAYER', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (175, 'SMALL', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (176, 'SNIPER', '4');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (177, 'SPEEDREADER', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (178, 'SPRINTER', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (179, 'STEP_ASIDE', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (180, 'STONE_SOUP', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (181, 'STOUT_HEARTED', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (182, 'STRIDER_COASTAL', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (183, 'STRIDER_DESERTS', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (184, 'STRIDER_MARSHES', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (185, 'STRIDER_ROCKY', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (186, 'STRIDER_TUNDRA', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (187, 'STRIDER_WOODLANDS', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (188, 'STRIKE_MIGHTY_BLOW', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (189, 'STRIKE_TO_INJURE', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (190, 'STRIKE_TO_STUN', 'WSB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (191, 'STRONG_BACK', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (192, 'STRONG_LEGS', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (193, 'STRING_MINDED', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (194, 'STRONG_SWIMMER', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (195, 'STURDY', 'SB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (196, 'SUAVE', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (197, 'SUPER_NUMERATE', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (198, 'SUPPORTIVE', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (199, 'SURE_SHOT', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (200, 'SURGERY', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (201, 'TENACIOUS', 'TB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (202, 'TINKER', 'DEXB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (203, 'TOWER_OF_MEMORIES', 'INTB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (204, 'TRAPPER', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (205, 'TRICK_RIDING', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (206, 'TUNNEL_RAT', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (207, 'UNSHAKABLE', 'WPB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (208, 'VERY_RESILIENT', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (209, 'VERY_STRONG', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (210, 'WAR_LEADER', 'FELB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (211, 'WAR_WIZARD', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (212, 'WARRIOR_BORN', '1');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (213, 'WATERMAN', 'AGB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (214, 'WEALTHY', 'NONE');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (215, 'WELL_PREPARED', 'IB');
INSERT IGNORE INTO talent(id, name, max_level) VALUE (216, 'WITCH', 'WPB');

INSERT IGNORE INTO characteristic(id, name) VALUE (1, 'WEAPON_SKILL');
INSERT IGNORE INTO characteristic(id, name) VALUE (2, 'BALLISTIC_SKILL');
INSERT IGNORE INTO characteristic(id, name) VALUE (3, 'STRENGTH');
INSERT IGNORE INTO characteristic(id, name) VALUE (4, 'TOUGHNESS');
INSERT IGNORE INTO characteristic(id, name) VALUE (5, 'INITIATIVE');
INSERT IGNORE INTO characteristic(id, name) VALUE (6, 'AGILITY');
INSERT IGNORE INTO characteristic(id, name) VALUE (7, 'DEXTERITY');
INSERT IGNORE INTO characteristic(id, name) VALUE (8, 'INTELLIGENCE');
INSERT IGNORE INTO characteristic(id, name) VALUE (9, 'WILLPOWER');
INSERT IGNORE INTO characteristic(id, name) VALUE (10, 'FELLOWSHIP');
INSERT IGNORE INTO characteristic(id, name) VALUE (11, 'WOUNDS');
INSERT IGNORE INTO characteristic(id, name) VALUE (12, 'MOVEMENT');
