INSERT INTO armor_category (name) VALUES ('SOFT_LEATHER');
INSERT INTO armor_category (name) VALUES ('BOILED_LEATHER');
INSERT INTO armor_category (name) VALUES ('MAIL');
INSERT INTO armor_category (name) VALUES ('PLATE');


INSERT INTO armor_penalty(name) VALUES ('MINUS_TEN_PERCEPTION');
INSERT INTO armor_penalty(name) VALUES ('MINUS_TEN_STEALTH');
INSERT INTO armor_penalty(name) VALUES ('MINUS_TWENTY_PERCEPTION');


INSERT INTO armor_quality (name) VALUES ('FLEXIBLE');
INSERT INTO armor_quality (name) VALUES ('IMPENETRABLE');
INSERT INTO armor_quality (name) VALUES ('PARTIAL');
INSERT INTO armor_quality (name) VALUES ('WEAKPOINTS');
INSERT INTO armor_quality (name) VALUES ('DURABLE');
INSERT INTO armor_quality (name) VALUES ('FINE');
INSERT INTO armor_quality (name) VALUES ('LIGHTWEIGHT');
INSERT INTO armor_quality (name) VALUES ('PRACTICAL');
INSERT INTO armor_quality (name) VALUES ('UGLY');
INSERT INTO armor_quality (name) VALUES ('SHODDY');
INSERT INTO armor_quality (name) VALUES ('UNRELIABLE');


INSERT INTO body_localization(name) VALUES ('HEAD');
INSERT INTO body_localization(name) VALUES ('RIGHT_ARM');
INSERT INTO body_localization(name) VALUES ('LEFT_ARM');
INSERT INTO body_localization(name) VALUES ('BODY');
INSERT INTO body_localization(name) VALUES ('RIGHT_LEG');
INSERT INTO body_localization(name) VALUES ('LEFT_LEG');


INSERT INTO weapon_group(name) VALUES ('BASIC');
INSERT INTO weapon_group(name) VALUES ('CAVALRY');
INSERT INTO weapon_group(name) VALUES ('FENCING');
INSERT INTO weapon_group(name) VALUES ('BRAWLING');
INSERT INTO weapon_group(name) VALUES ('FLAIL');
INSERT INTO weapon_group(name) VALUES ('PARRY');
INSERT INTO weapon_group(name) VALUES ('POLEARM');
INSERT INTO weapon_group(name) VALUES ('TWO_HANDED');
INSERT INTO weapon_group(name) VALUES ('BLACKPOWDER');
INSERT INTO weapon_group(name) VALUES ('BOW');
INSERT INTO weapon_group(name) VALUES ('CROSSBOW');
INSERT INTO weapon_group(name) VALUES ('ENGINEERING');
INSERT INTO weapon_group(name) VALUES ('ENTANGLING');
INSERT INTO weapon_group(name) VALUES ('EXPLOSIVES');
INSERT INTO weapon_group(name) VALUES ('SLING');
INSERT INTO weapon_group(name) VALUES ('THROWING');


INSERT INTO weapon_quality(name) VALUES ('ACCURATE');
INSERT INTO weapon_quality(name) VALUES ('BLACKPOWDER');
INSERT INTO weapon_quality(name) VALUES ('BLAST');
INSERT INTO weapon_quality(name) VALUES ('DAMAGING');
INSERT INTO weapon_quality(name) VALUES ('DEFENSIVE');
INSERT INTO weapon_quality(name) VALUES ('DISTRACT');
INSERT INTO weapon_quality(name) VALUES ('ENTANGLE');
INSERT INTO weapon_quality(name) VALUES ('FAST');
INSERT INTO weapon_quality(name) VALUES ('HACK');
INSERT INTO weapon_quality(name) VALUES ('IMPACT');
INSERT INTO weapon_quality(name) VALUES ('IMPALE');
INSERT INTO weapon_quality(name) VALUES ('PENETRATING');
INSERT INTO weapon_quality(name) VALUES ('PISTOL');
INSERT INTO weapon_quality(name) VALUES ('PRECISE');
INSERT INTO weapon_quality(name) VALUES ('PUMMEL');
INSERT INTO weapon_quality(name) VALUES ('REPEATER');
INSERT INTO weapon_quality(name) VALUES ('SHIELD');
INSERT INTO weapon_quality(name) VALUES ('TRAP_BLADE');
INSERT INTO weapon_quality(name) VALUES ('TWO_HANDED');
INSERT INTO weapon_quality(name) VALUES ('UNBREAKABLE');
INSERT INTO weapon_quality(name) VALUES ('WRAP');
INSERT INTO weapon_quality(name) VALUES ('DANGEROUS');
INSERT INTO weapon_quality(name) VALUES ('IMPRECISE');
INSERT INTO weapon_quality(name) VALUES ('RELOAD');
INSERT INTO weapon_quality(name) VALUES ('SLOW');
INSERT INTO weapon_quality(name) VALUES ('TIRING');
INSERT INTO weapon_quality(name) VALUES ('UNDAMAGING');


INSERT INTO weapon_reach(name) VALUES ('AVERAGE');
INSERT INTO weapon_reach(name) VALUES ('LONG');
INSERT INTO weapon_reach(name) VALUES ('MASSIVE');
INSERT INTO weapon_reach(name) VALUES ('PERSONAL');
INSERT INTO weapon_reach(name) VALUES ('RANGED');
INSERT INTO weapon_reach(name) VALUES ('SHORT');
INSERT INTO weapon_reach(name) VALUES ('VARIES');
INSERT INTO weapon_reach(name) VALUES ('VERY_LONG');
INSERT INTO weapon_reach(name) VALUES ('VERY_SHORT');


INSERT INTO weapon_type(name) VALUES ('MELEE');
INSERT INTO weapon_type(name) VALUES ('RANGED');


INSERT INTO skill(name) VALUE ('ART_CARTOGRAPHY');
INSERT INTO skill(name) VALUE ('ART_ENGRAVING');
INSERT INTO skill(name) VALUE ('ART_MOSAICS');
INSERT INTO skill(name) VALUE ('ART_PAINTING');
INSERT INTO skill(name) VALUE ('ART_SCULPTURE');
INSERT INTO skill(name) VALUE ('ART_TATTOO');
INSERT INTO skill(name) VALUE ('ART_WEAVING');
INSERT INTO skill(name) VALUE ('ATHLETICS');
INSERT INTO skill(name) VALUE ('BRIBERY');
INSERT INTO skill(name) VALUE ('CHARM');
INSERT INTO skill(name) VALUE ('CHARM_ANIMAL');
INSERT INTO skill(name) VALUE ('CLIMB');
INSERT INTO skill(name) VALUE ('COOL');
INSERT INTO skill(name) VALUE ('CONSUME_ALCOHOL');
INSERT INTO skill(name) VALUE ('DODGE');
INSERT INTO skill(name) VALUE ('DRIVE');
INSERT INTO skill(name) VALUE ('ENDURANCE');
INSERT INTO skill(name) VALUE ('ENTERTAIN_ACTING');
INSERT INTO skill(name) VALUE ('ENTERTAIN_COMEDY');
INSERT INTO skill(name) VALUE ('ENTERTAIN_SINGING');
INSERT INTO skill(name) VALUE ('ENTERTAIN_STORYTELLING');
INSERT INTO skill(name) VALUE ('GAMBLE');
INSERT INTO skill(name) VALUE ('GOSSIP');
INSERT INTO skill(name) VALUE ('HAGGLE');
INSERT INTO skill(name) VALUE ('INTIMIDATE');
INSERT INTO skill(name) VALUE ('INTUITION');
INSERT INTO skill(name) VALUE ('LEADERSHIP');
INSERT INTO skill(name) VALUE ('MELEE_BASIC');
INSERT INTO skill(name) VALUE ('MELEE_BRAWLING');
INSERT INTO skill(name) VALUE ('MELEE_CAVALRY');
INSERT INTO skill(name) VALUE ('MELEE_FENCING');
INSERT INTO skill(name) VALUE ('MELEE_FLAIL');
INSERT INTO skill(name) VALUE ('MELEE_PARRY');
INSERT INTO skill(name) VALUE ('MELEE_POLEARM');
INSERT INTO skill(name) VALUE ('MELEE_TWO_HANDED');
INSERT INTO skill(name) VALUE ('NAVIGATION');
INSERT INTO skill(name) VALUE ('OUTDOOR_SURVIVAL');
INSERT INTO skill(name) VALUE ('PERCEPTION');
INSERT INTO skill(name) VALUE ('RIDE_DEMIGRYPH');
INSERT INTO skill(name) VALUE ('RIDE_GREAT_WOLF');
INSERT INTO skill(name) VALUE ('RIDE_GRIFFON');
INSERT INTO skill(name) VALUE ('RIDE_HORSE');
INSERT INTO skill(name) VALUE ('RIDE_PEGASUS');
INSERT INTO skill(name) VALUE ('ROW');
INSERT INTO skill(name) VALUE ('STEALTH_RURAL');
INSERT INTO skill(name) VALUE ('STEALTH_UNDERGROUND');
INSERT INTO skill(name) VALUE ('STEALTH_URBAN');
INSERT INTO skill(name) VALUE ('ANIMAL_CARE');
INSERT INTO skill(name) VALUE ('ANIMAL_TRAINING_DEMIGRYPH');
INSERT INTO skill(name) VALUE ('ANIMAL_TRAINING_DOG');
INSERT INTO skill(name) VALUE ('ANIMAL_TRAINING_HORSE');
INSERT INTO skill(name) VALUE ('ANIMAL_TRAINING_PEGASUS');
INSERT INTO skill(name) VALUE ('ANIMAL_TRAINING_PIGEON');
INSERT INTO skill(name) VALUE ('CHANNELLING_AQSHY');
INSERT INTO skill(name) VALUE ('CHANNELLING_AZYR');
INSERT INTO skill(name) VALUE ('CHANNELLING_CHAMON');
INSERT INTO skill(name) VALUE ('CHANNELLING_DHAR');
INSERT INTO skill(name) VALUE ('CHANNELLING_GHUR');
INSERT INTO skill(name) VALUE ('CHANNELLING_GHYRAN');
INSERT INTO skill(name) VALUE ('CHANNELLING_HYSH');
INSERT INTO skill(name) VALUE ('CHANNELLING_SHYISH');
INSERT INTO skill(name) VALUE ('CHANNELLING_ULGU');
INSERT INTO skill(name) VALUE ('EVALUATE');
INSERT INTO skill(name) VALUE ('HEAL');
INSERT INTO skill(name) VALUE ('LANGUAGE_BATTLE_TONGUE');
INSERT INTO skill(name) VALUE ('LANGUAGE_BRETONNIAN');
INSERT INTO skill(name) VALUE ('LANGUAGE_CLASSICAL');
INSERT INTO skill(name) VALUE ('LANGUAGE_GUILDER');
INSERT INTO skill(name) VALUE ('LANGUAGE_KHAZALID');
INSERT INTO skill(name) VALUE ('LANGUAGE_MAGICK');
INSERT INTO skill(name) VALUE ('LANGUAGE_THIEF');
INSERT INTO skill(name) VALUE ('LANGUAGE_TILEAN');
INSERT INTO skill(name) VALUE ('LORE_ENGINEERING');
INSERT INTO skill(name) VALUE ('LORE_GEOLOGY');
INSERT INTO skill(name) VALUE ('LORE_HERALDRY');
INSERT INTO skill(name) VALUE ('LORE_HISTORY');
INSERT INTO skill(name) VALUE ('LORE_LAW');
INSERT INTO skill(name) VALUE ('LORE_MAGICK');
INSERT INTO skill(name) VALUE ('LORE_METALLURGY');
INSERT INTO skill(name) VALUE ('LORE_SCIENCE');
INSERT INTO skill(name) VALUE ('LORE_THEOLOGY');
INSERT INTO skill(name) VALUE ('PERFORM_ACROBATICS');
INSERT INTO skill(name) VALUE ('PERFORM_CLOWNING');
INSERT INTO skill(name) VALUE ('PERFORM_DANCING');
INSERT INTO skill(name) VALUE ('PERFORM_FIREBREATHING');
INSERT INTO skill(name) VALUE ('PERFORM_JUGGLING');
INSERT INTO skill(name) VALUE ('PERFORM_MIMING');
INSERT INTO skill(name) VALUE ('PERFORM_ROPE_WALKING');
INSERT INTO skill(name) VALUE ('PICK_LOCK');
INSERT INTO skill(name) VALUE ('PLAY_BAGPIPE');
INSERT INTO skill(name) VALUE ('PLAY_LUTE');
INSERT INTO skill(name) VALUE ('PLAY_HARP');
INSERT INTO skill(name) VALUE ('PLAY_HORN');
INSERT INTO skill(name) VALUE ('PLAY_VIOLIN');
INSERT INTO skill(name) VALUE ('PRAY');
INSERT INTO skill(name) VALUE ('RANGED_BLACKPOWDER');
INSERT INTO skill(name) VALUE ('RANGED_BOW');
INSERT INTO skill(name) VALUE ('RANGED_CROSSBOW');
INSERT INTO skill(name) VALUE ('RANGED_ENGINEERING');
INSERT INTO skill(name) VALUE ('RANGED_ENTANGLING');
INSERT INTO skill(name) VALUE ('RANGED_EXPLOSIVES');
INSERT INTO skill(name) VALUE ('RANGED_SLING');
INSERT INTO skill(name) VALUE ('RANGED_THROWING');
INSERT INTO skill(name) VALUE ('RESEARCH');
INSERT INTO skill(name) VALUE ('SAIL_BARGE');
INSERT INTO skill(name) VALUE ('SAIL_CARAVEL');
INSERT INTO skill(name) VALUE ('SAIL_COG');
INSERT INTO skill(name) VALUE ('SAIL_FRIGATE');
INSERT INTO skill(name) VALUE ('SAIL_WOLFSHIP');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_GREY_ORDER');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_GUILD');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_RANGER');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_SCOUT');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_THIEF');
INSERT INTO skill(name) VALUE ('SECRET_SIGNS_VAGABOND');
INSERT INTO skill(name) VALUE ('SET_TRAP');
INSERT INTO skill(name) VALUE ('SLEIGHT_OF_HAND');
INSERT INTO skill(name) VALUE ('SWIM');
INSERT INTO skill(name) VALUE ('TRACK');
INSERT INTO skill(name) VALUE ('TRADE_APOTHECARY');
INSERT INTO skill(name) VALUE ('TRADE_CALLIGRAPHER');
INSERT INTO skill(name) VALUE ('TRADE_CHANDLER');
INSERT INTO skill(name) VALUE ('TRADE_CARPENTER');
INSERT INTO skill(name) VALUE ('TRADE_COOK');
INSERT INTO skill(name) VALUE ('TRADE_EMBALMER');
INSERT INTO skill(name) VALUE ('TRADE_SMITH');
INSERT INTO skill(name) VALUE ('TRADE_TANNER');

INSERT INTO talent(name, max_level) VALUE ('ACCURATE_SHOT', 'BSB');
INSERT INTO talent(name, max_level) VALUE ('ACUTE_SENSE_SIGHT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ACUTE_SENSE_SMELL', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ACUTE_SENSE_HEARING', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ACUTE_SENSE_FEEL', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ACUTE_SENSE_TASTE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('AETHYRIC_ATTUNEMENT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ALLEY_CAT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('AMBIDEXTROUS', '2');
INSERT INTO talent(name, max_level) VALUE ('ANIMAL_AFFINITY', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_BEASTS', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_DEATH', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_FIRE', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_HEAVENS', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_METAL', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_SHADOW', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_LIGHT', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_LIFE', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_HEDGECRAFT', '1');
INSERT INTO talent(name, max_level) VALUE ('ARCANE_MAGIC_NECROMANCY', '1');
INSERT INTO talent(name, max_level) VALUE ('ARGUMENTATIVE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('ARTISTIC', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('ATTRACTIVE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('BATTLE_RAGE', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('BEAT_BLADE', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('BENEATH_NOTICE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('BERSERK_CHARGE', 'SB');
INSERT INTO talent(name, max_level) VALUE ('BLATHER', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('BLESS_MANANN', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_MORR', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_MYRMIDIA', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_RANALD', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_RHYA', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_SHALLYA', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_SIGMAR', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_TAAL', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_ULRIC', '1');
INSERT INTO talent(name, max_level) VALUE ('BLESS_VERENA', '1');
INSERT INTO talent(name, max_level) VALUE ('BOOKISH', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('BREAK_AND_ENTER', 'SB');
INSERT INTO talent(name, max_level) VALUE ('BRIBER', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('CARDSHARP', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('CAREFUL_STRIKE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('CAROUSER', 'TB');
INSERT INTO talent(name, max_level) VALUE ('CATFALL', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('CAT_TONGUED', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('CHAOS_MAGIC_NURGLE', '1');
INSERT INTO talent(name, max_level) VALUE ('CHAOS_MAGIC_SLAANESH', '1');
INSERT INTO talent(name, max_level) VALUE ('CHAOS_MAGIC_TZEENTCH', '1');
INSERT INTO talent(name, max_level) VALUE ('COMBAT_AWARE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('COMBAT_MASTER', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('COMBAT_REFLEXES', 'IB');
INSERT INTO talent(name, max_level) VALUE ('COMMANDING_PRESENCE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('CONCOCT', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('CONTORTIONIST', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('COOLHEADED', '1');
INSERT INTO talent(name, max_level) VALUE ('CRACK_THE_WHIP', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('CRAFTSMAN', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('CRIMINAL', 'NONE');
INSERT INTO talent(name, max_level) VALUE ('DEADEYE_SHOT', '1');
INSERT INTO talent(name, max_level) VALUE ('DEALMAKER', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('DETECT_ARTEFACT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('DICEMAN', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('DIRTY_FIGHTING', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('DISARM', 'IB');
INSERT INTO talent(name, max_level) VALUE ('DISTRACT', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('DOOMED', '1');
INSERT INTO talent(name, max_level) VALUE ('DRILLED', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('DUAL_WIELDER', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('EMBEZZLE', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('ENCLOSED_FIGHTER', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('ETIQUETTE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('FAST_HANDS', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('FAST_SHOT', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_BEASTMEN', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_GREENSKINS', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_OUTLAWS', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_VAMPIRES', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_WATCHMEN', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEARLESS_WITCHES', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('FEINT', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('FIELD_DRESSING', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('FISHERMAN', 'IB');
INSERT INTO talent(name, max_level) VALUE ('FLAGELLANT', 'TB');
INSERT INTO talent(name, max_level) VALUE ('FLEE', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('FLEET_FOOTED', '1');
INSERT INTO talent(name, max_level) VALUE ('FRENZY', '1');
INSERT INTO talent(name, max_level) VALUE ('FRIGHTENING', 'SB');
INSERT INTO talent(name, max_level) VALUE ('FURIOUS_ASSAULT', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('GREGARIOUS', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('GUNNER', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('HARDY', 'TB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_BEASTMEN', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_GRENSKINS', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_MONSTERS', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_OUTLAWS', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_SIGMARITES', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_UNDEAD', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HATRED_WITCHES', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('HOLY_HATRED', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('HOLY_VISIONS', 'IB');
INSERT INTO talent(name, max_level) VALUE ('HUNTERS_EYE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('IMPASSIONED_ZEAL', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('IMPLACABLE', 'TB');
INSERT INTO talent(name, max_level) VALUE ('IN_FIGHTER', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('INSPIRING', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('INSTINCTIVE_DICTION', 'IB');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_MANANN', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_MORR', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_MYRMIDIA', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_RANALD', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_RHYA', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_SHALLYA', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_SIGMAR', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_TAAL', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_ULRIC', '1');
INSERT INTO talent(name, max_level) VALUE ('INVOKE_VERENA', '1');
INSERT INTO talent(name, max_level) VALUE ('IRON_JAW', 'TB');
INSERT INTO talent(name, max_level) VALUE ('IRON_WILL', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('JUMP_UP', '1');
INSERT INTO talent(name, max_level) VALUE ('KINGPIN', '1');
INSERT INTO talent(name, max_level) VALUE ('LIGHTNING_REFLEXES', '1');
INSERT INTO talent(name, max_level) VALUE ('LINGUISTICS', 'IB');
INSERT INTO talent(name, max_level) VALUE ('LIP_READING', 'IB');
INSERT INTO talent(name, max_level) VALUE ('LUCK', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('MAGICAL_SENSE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('MAGIC_RESISTANCE', '1');
INSERT INTO talent(name, max_level) VALUE ('MAGNUM_OPUS', 'NONE');
INSERT INTO talent(name, max_level) VALUE ('MARKSMAN', '1');
INSERT INTO talent(name, max_level) VALUE ('MASTER_OF_DISGUISE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('MASTER_ORATOR', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('MASTER_TRADESMAN', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('MENACING', 'SB');
INSERT INTO talent(name, max_level) VALUE ('MIMIC', 'IB');
INSERT INTO talent(name, max_level) VALUE ('NIGHT_VISION', 'IB');
INSERT INTO talent(name, max_level) VALUE ('NIMBLE_FINGERED', '1');
INSERT INTO talent(name, max_level) VALUE ('NOBLE_BLOOD', '1');
INSERT INTO talent(name, max_level) VALUE ('NOSE_FOR_TROUBLE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('NUMISMATICS', 'IB');
INSERT INTO talent(name, max_level) VALUE ('OLD_SALT', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('ORIENTATION', 'IB');
INSERT INTO talent(name, max_level) VALUE ('PANHANDLE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('PERFECT_PITCH', 'IB');
INSERT INTO talent(name, max_level) VALUE ('PETTY_MAGIC', '1');
INSERT INTO talent(name, max_level) VALUE ('PHARMACIST', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('PILOT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('PUBLIC_SPEAKER', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('PURE_SOUL', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('RAPID_RELOAD', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('REACTION_STRIKE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('READ_WRITE', '1');
INSERT INTO talent(name, max_level) VALUE ('RELENTLESS', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('RESISTANCE', 'TB');
INSERT INTO talent(name, max_level) VALUE ('RESOLUTE', 'SB');
INSERT INTO talent(name, max_level) VALUE ('REVERSAL', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('RIPOSTE', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('RIVER_GUIDE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('ROBUST', 'TB');
INSERT INTO talent(name, max_level) VALUE ('ROUGHRIDER', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('ROVER', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('SAVANT', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SAVVY', '1');
INSERT INTO talent(name, max_level) VALUE ('SCALE_SHEER_SURFACE', 'SB');
INSERT INTO talent(name, max_level) VALUE ('SCHEMER', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SEA_LEGS', 'TB');
INSERT INTO talent(name, max_level) VALUE ('SEASONED_TRAVELLER', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SECOND_SIGHT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('SECRET_IDENTITY', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SHADOW', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('SHARP', '1');
INSERT INTO talent(name, max_level) VALUE ('SHARPSHOOTER', '1');
INSERT INTO talent(name, max_level) VALUE ('SHIELDSMAN', 'SB');
INSERT INTO talent(name, max_level) VALUE ('SIXTH_SENSE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('SLAYER', '1');
INSERT INTO talent(name, max_level) VALUE ('SMALL', '1');
INSERT INTO talent(name, max_level) VALUE ('SNIPER', '4');
INSERT INTO talent(name, max_level) VALUE ('SPEEDREADER', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SPRINTER', 'SB');
INSERT INTO talent(name, max_level) VALUE ('STEP_ASIDE', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STONE_SOUP', 'TB');
INSERT INTO talent(name, max_level) VALUE ('STOUT_HEARTED', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_COASTAL', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_DESERTS', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_MARSHES', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_ROCKY', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_TUNDRA', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIDER_WOODLANDS', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('STRIKE_MIGHTY_BLOW', 'SB');
INSERT INTO talent(name, max_level) VALUE ('STRIKE_TO_INJURE', 'IB');
INSERT INTO talent(name, max_level) VALUE ('STRIKE_TO_STUN', 'WSB');
INSERT INTO talent(name, max_level) VALUE ('STRONG_BACK', 'SB');
INSERT INTO talent(name, max_level) VALUE ('STRONG_LEGS', 'SB');
INSERT INTO talent(name, max_level) VALUE ('STRING_MINDED', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('STRONG_SWIMMER', 'SB');
INSERT INTO talent(name, max_level) VALUE ('STURDY', 'SB');
INSERT INTO talent(name, max_level) VALUE ('SUAVE', '1');
INSERT INTO talent(name, max_level) VALUE ('SUPER_NUMERATE', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('SUPPORTIVE', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('SURE_SHOT', 'IB');
INSERT INTO talent(name, max_level) VALUE ('SURGERY', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('TENACIOUS', 'TB');
INSERT INTO talent(name, max_level) VALUE ('TINKER', 'DEXB');
INSERT INTO talent(name, max_level) VALUE ('TOWER_OF_MEMORIES', 'INTB');
INSERT INTO talent(name, max_level) VALUE ('TRAPPER', 'IB');
INSERT INTO talent(name, max_level) VALUE ('TRICK_RIDING', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('TUNNEL_RAT', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('UNSHAKABLE', 'WPB');
INSERT INTO talent(name, max_level) VALUE ('VERY_RESILIENT', '1');
INSERT INTO talent(name, max_level) VALUE ('VERY_STRONG', '1');
INSERT INTO talent(name, max_level) VALUE ('WAR_LEADER', 'FELB');
INSERT INTO talent(name, max_level) VALUE ('WAR_WIZARD', '1');
INSERT INTO talent(name, max_level) VALUE ('WARRIOR_BORN', '1');
INSERT INTO talent(name, max_level) VALUE ('WATERMAN', 'AGB');
INSERT INTO talent(name, max_level) VALUE ('WEALTHY', 'NONE');
INSERT INTO talent(name, max_level) VALUE ('WELL_PREPARED', 'IB');
INSERT INTO talent(name, max_level) VALUE ('WITCH', 'WPB');

INSERT INTO characteristic(name) VALUE ('WEAPON_SKILL');
INSERT INTO characteristic(name) VALUE ('BALLISTIC_SKILL');
INSERT INTO characteristic(name) VALUE ('STRENGTH');
INSERT INTO characteristic(name) VALUE ('TOUGHNESS');
INSERT INTO characteristic(name) VALUE ('INITIATIVE');
INSERT INTO characteristic(name) VALUE ('AGILITY');
INSERT INTO characteristic(name) VALUE ('DEXTERITY');
INSERT INTO characteristic(name) VALUE ('INTELLIGENCE');
INSERT INTO characteristic(name) VALUE ('WILLPOWER');
INSERT INTO characteristic(name) VALUE ('FELLOWSHIP');
INSERT INTO characteristic(name) VALUE ('WOUNDS');
INSERT INTO characteristic(name) VALUE ('MOVEMENT');
